apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "ejbca-k8s-csr-signer.labels" . | nindent 4 }}
  name: {{ include "ejbca-k8s-csr-signer.name" . }}-secret-reader-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "ejbca-k8s-csr-signer.labels" . | nindent 4 }}
  name: {{ include "ejbca-k8s-csr-signer.name" . }}-secret-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ejbca-k8s-csr-signer.name" . }}-secret-reader-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ejbca-k8s-csr-signer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}